### ISSUE TITLE
Variables, spacing and em measures

### ISSUE THREAD

**Issue by danielhutch** [danielhutch/danielhutch.github.io#3]
I’m using variables for consistent spacing and am specifying it in ems e.g.

`$space-medium: 1.5em;
`
However in Chrome, when specifying a margin 1.5em is displaying as 36px (not the expected 24px).

![image](https://cloud.githubusercontent.com/assets/3185388/25226231/1f8a0b4e-25bc-11e7-887d-b4a82687fd4c.png)

My default font size in Chrome is set to medium (16px). Should I specify spacing and widths in px and only use ems for fonts?

**Comment by orangespaceman** [comment]
When you set a value such as margin or padding using `em` its value will depend on the font size. 

If you set `font-size: 1em` (which defaults to `16px`) then `margin-bottom: 1em` will also be `16px`

If you set `font-size: 1.5em` (which becomes to `24px`) then `margin-bottom: 1em` will be `24px`

If you set `font-size: 1em` (`16px`) then `margin-bottom: 1.5em` will be `24px`

If you set `font-size: 1.5em` (`24px`) then `margin-bottom: 1.5em` will be `36px` (24 + 12)

Using `em` is further complicated by inheritance, if you set a font-size on a parent element then this is factored into the calculations, which quickly become complex.

Even if you set font sizes in pixels, if it is larger than 1em (16px) then the value of 1em won't be what you were assuming.

The easiest way around this in your situation would be to use `rem` instead of `em` - this takes its value from the font-size of the `html` element _only_, and so you can assume that `1rem` will always be equal to `16px` regardless of the font size.

It's not a perfect solution but for now it's generally the best approach to default to.

Further reading: 

 - http://engageinteractive.co.uk/blog/em-vs-rem-vs-px
 - https://www.lullabot.com/articles/scaling-css-components-with-bem-rems-ems
 - https://zellwk.com/blog/rem-vs-em/
