### ISSUE TITLE
Link style

### ISSUE THREAD

**Issue by danielhutch** [danielhutch/danielhutch.github.io#4]
A link has been added within the list item div containing a project.

https://danielhutch.github.io/

A hover style has been defined but only works on the client and not the title (as expected).

The title colour has been specified at a component level and not inherited — could this be conflicting with the hover styling?

**Comment by orangespaceman** [comment]
This issue is a little hard to understand, it might be better explained with a screenshot and/or referencing the actual class names of the elements. 

_Ambiguity is the mother of all thingy_

**Comment by orangespaceman** [comment]
https://github.com/danielhutch/danielhutch.github.io/blob/master/_includes/components/project-list/project-list.scss#L72

You shouldn't need the `a` at the start of the style definition. This is the rationale for using the BEM naming convention - no need to make your styling selectors so specific

```
/* wrong */
a.project-list__post-link:hover {

/* correct */
.project-list__post-link:hover {
```

**Comment by orangespaceman** [comment]
Here is the HTML structure of the `project-list` component: 

```
<a class="project-list__post-link" href="{{ post.url | prepend: site.baseurl }}">
    <div class="project-list__client">...</div>
    <div class="project-list__title">...</div>
</a>
```

The issue you are describing is that you have set a text colour and hover colour on the containing `project-list__post-link` element, this is inherited by the `project-list__client` which is why it changes colour on hover, but you have set a different colour on the `project-list__title` element which is more specific and so overrides the hover colour set on the parent.

The easiest solution would be to move the hover colour declarations, something like this in `project-list.scss`: 

```
.project-list__post-link {
    text-decoration: none;
}

.project-list__post-link:hover {
    text-decoration: underline;
}

.project-list__client {
    color: $colour-darkgrey;
    font-size: $font-size-medium;
}

.project-list__post-link:hover .project-list__client {
    color: $colour-green;
}

.project-list__title {
    color: $colour-midgrey;
}

.project-list__post-link:hover .project-list__title {
    color: $colour-green;
}
```

This is the only time you will likely use more than one selector, when you want a style to apply when a parent element has been hovered over
